name: Maven Build

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: buildtools/doodle-specification-maven
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Check Codingstyle
        run: ./mvnw spotless:check

      - name: Build with Maven
        run: ./mvnw package -B
